---
- name: Set loglevel
  become: true
  replace:
    path: /usr/share/etherpad-lite/settings.json
    regexp: '"loglevel":.*,'
    replace: '"loglevel": "{{ bbb_etherpad_log_level }}",'
  notify: restart etherpad
